Mqtt service added.
Project-Software-Engineering/lorafy-api pull request #11
Opened 2022-12-13 11:40 UTC by ababsmuc

2022-12-13 11:44 UTC, stefank02 approved these changes
LGTM

2022-12-13 11:44 UTC, stijnstroeve requested changes

2022-12-13 11:44 UTC, stijnstroeve commented on LorafyAPI/LorafyAPI.csproj
> +    <PackageReference Include="MQTTnet" Version="4.1.4.563" />
Why have you added both MQTTnet and M2Mqtt?

2022-12-13 11:44 UTC, stijnstroeve commented on LorafyAPI/appsettings.Development.json
> +  "MQTT_variables": {
Please add to git ignore :)

2022-12-13 11:44 UTC, stijnstroeve commented on LorafyAPI/MQTT_BackgroundService.cs
> +public class MQTT_BackgroundService : BackgroundService
Can you remove the `_` from the class name? Its a convention to use 1 casing at once.

2022-12-13 11:44 UTC, stijnstroeve commented on LorafyAPI/MQTT_BackgroundService.cs
> +
Can you format the document so there is only 1 whitespace in between?

2022-12-13 11:44 UTC, stijnstroeve commented on LorafyAPI/MQTT_BackgroundService.cs
> +using uPLibrary.Networking.M2Mqtt.Messages;
Please a newline after the imports

2022-12-15 09:29 UTC, stefank02 approved these changes
LGTM

2022-12-15 09:29 UTC, stijnstroeve approved these changes
LGTM :D

2022-12-15 09:29 UTC, merged